spring.application.name=UserRegistration
server.port=7860

# ===============================
# DATABASE CONNECTION (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-flat-dust-ao56u4g4-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_pt1kS0OXfaJL
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update